import * as m from '$lib/paraglide/messages.js';
import { getLocale } from '$lib/paraglide/runtime.js';

export interface QuantityParts {
	/** Formatted number, locale-aware (e.g. "1,524"). */
	value: string;
	/** Unit code (e.g. "kilometre"), or null when the value is unitless. */
	unit: string | null;
}

// Hardcoded fallbacks for unit symbols that aren't yet in the i18n bundle
// (Wikidata-derived symbols are autogenerated on export — these are universal
// enough to inline here so the UI works before the next data export).
const SYMBOL_FALLBACK: Record<string, string> = {
	day: 'd',
	minute: 'min',
	degree: '°',
	square_metre: 'm²'
};

// Units whose short symbols are widely recognized — skip the explanatory
// tooltip on the unit cell. Everything else gets a tooltip with the long name
// so readers can decode "M⊕", "g/cm³", "AU", etc.
const OBVIOUS_UNITS = new Set([
	'kilometre',
	'metre',
	'centimetre',
	'kilogram',
	'gram',
	'tonne',
	'hour',
	'minute',
	'day',
	'kelvin',
	'degree_celsius',
	'degree_fahrenheit',
	'magnitude',
	'degree',
	'square_metre'
]);

export function ucfirst(s: string): string {
	return s.charAt(0).toUpperCase() + s.slice(1);
}

function lookupMessage(key: string): string | null {
	const fn = (m as unknown as Record<string, (() => string) | undefined>)[key];
	return fn ? fn() : null;
}

export function formatUnit(unit: string, short?: boolean): string {
	const symbolKey = short ? `unit_symbol_${unit}` : `unit_name_${unit}`;
	const value = lookupMessage(symbolKey);
	if (value) return value;
	if (short && SYMBOL_FALLBACK[unit]) return SYMBOL_FALLBACK[unit];
	console.warn(`Missing unit label: ${symbolKey}`);
	return unit.replace(/_/g, ' ');
}

/** Long-form unit name for tooltips, falling back to the short symbol. */
export function unitFullName(unit: string): string {
	return lookupMessage(`unit_name_${unit}`) ?? formatUnit(unit, true);
}

export function unitNeedsTooltip(unit: string): boolean {
	return !OBVIOUS_UNITS.has(unit);
}

/** Intl rounding options that keep ~3 digits of precision (4+ digit integers unchanged). */
export function precisionOptions(
	n: number
): Pick<Intl.NumberFormatOptions, 'maximumFractionDigits'> {
	const intDigits = Math.floor(Math.abs(n)) === 0 ? 0 : Math.floor(Math.log10(Math.abs(n))) + 1;
	return { maximumFractionDigits: Math.max(0, 3 - intDigits) };
}

export function formatNumber(n: number): string {
	if (!Number.isFinite(n)) return String(n);
	return n.toLocaleString(getLocale(), precisionOptions(n));
}

export function formatQuantityParts(q: { value: number; unit: string }): QuantityParts {
	return { value: formatNumber(q.value), unit: q.unit };
}

export function formatCurrency(q: { value: number; currency: string }): string {
	return new Intl.NumberFormat(getLocale(), {
		style: 'currency',
		currency: q.currency
	}).format(q.value);
}
