name: test data

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v6
        with:
          python-version-file: data/pyproject.toml

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install dev dependencies
        run: cd data && uv sync --locked --dev

      - uses: pre-commit/action@v3.0.1
